"use client";

import { Handle, Position, type NodeProps } from "reactflow";
import { Code2, Cpu, Database, Globe, Lock, Monitor, Shield, Zap } from "lucide-react";

const ICONS = {
  monitor: Monitor,
  shield: Shield,
  cpu: Cpu,
  database: Database,
  globe: Globe,
  lock: Lock,
  zap: Zap,
};

const LAYER_COLORS: Record<string, { border: string; glow: string; tag: string }> = {
  client: { border: "#5eead4", glow: "rgba(94,234,212,0.28)", tag: "#00ff9f" },
  gateway: { border: "#fbbf24", glow: "rgba(251,191,36,0.28)", tag: "#ffb020" },
  service: { border: "#38bdf8", glow: "rgba(56,189,248,0.28)", tag: "#00f5ff" },
  data: { border: "#a78bfa", glow: "rgba(167,139,250,0.28)", tag: "#a78bfa" },
  external: { border: "#fb7185", glow: "rgba(251,113,133,0.28)", tag: "#ff5f7d" },
};

export default function ArchitectureNode({ data, selected }: NodeProps) {
  const layer = (data.layer as string) || "service";
  const style = LAYER_COLORS[layer] || LAYER_COLORS.service;
  const Icon = ICONS[(data.icon as keyof typeof ICONS) || "cpu"] || Cpu;

  const guidedFocus = Boolean(data.__focused);
  return (
    <div
      className="group rounded-2xl border bg-slate-950/55 px-4 py-3 text-slate-100 transition-all duration-200 will-change-transform"
      style={{
        minWidth: 200,
        minHeight: 120,
        borderColor: selected ? "#00f5ff" : style.border,
        boxShadow: selected
          ? "0 0 0 1px rgba(0,245,255,0.7), 0 0 26px rgba(0,245,255,0.32)"
          : `0 0 0 1px ${style.glow}, 0 10px 25px rgba(2,8,24,0.55)`,
        transform: guidedFocus ? "scale(1.12)" : selected ? "scale(1.1)" : "scale(1)",
      }}
      title={String(data.description || data.label || "")}
    >
      <Handle type="target" position={Position.Top} className="!h-2.5 !w-2.5 !border-2 !border-slate-100 !bg-cyan-300" />
      <div className="mb-2 flex items-start justify-between gap-2">
        <div className="flex items-center gap-2">
          <Icon size={15} color={style.tag} />
          <span className="text-base font-bold leading-5 text-white [text-shadow:0_1px_4px_rgba(0,0,0,0.55)]">
            {data.label as string}
          </span>
        </div>
        <span className="rounded-full border px-2 py-0.5 text-[9px] uppercase tracking-[0.15em]" style={{ borderColor: `${style.tag}66`, color: style.tag }}>
          {layer}
        </span>
      </div>
      <div className="mt-2 flex flex-wrap gap-1.5 text-[12px]">
        <span className="flex items-center gap-1 rounded-md border border-cyan-300/35 bg-cyan-300/10 px-2 py-0.5 text-cyan-200">
          <Code2 size={11} />
          Stack
        </span>
        <span className="rounded-md border border-cyan-300/35 bg-slate-900/50 px-2 py-0.5 text-slate-200">
          {(data.tech as string) || "Runtime stack generated by AI"}
        </span>
      </div>
      {data.description && (
        <p className="mt-2 text-[11px] leading-4 text-slate-300">
          {String(data.description)}
        </p>
      )}
      <Handle type="source" position={Position.Bottom} className="!h-2.5 !w-2.5 !border-2 !border-slate-100 !bg-fuchsia-300" />
    </div>
  );
}
