"use client";

import { useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  BookOpenCheck,
  Download,
  Expand,
  FileImage,
  FileJson,
  FileText,
  Sparkles,
} from "lucide-react";

interface ViewerToolbarProps {
  onToggleImmersive: () => void;
  onStartWalkthrough: () => void;
  immersive: boolean;
  walkthroughActive: boolean;
  architecture?: {
    nodes?: unknown[];
    edges?: unknown[];
    title?: string;
    summary?: string;
    techStack?: unknown[];
  } | null;
}

export default function ViewerToolbar({
  onToggleImmersive,
  onStartWalkthrough,
  immersive,
  walkthroughActive,
  architecture,
}: ViewerToolbarProps) {
  const [exportOpen, setExportOpen] = useState(false);
  const [exporting, setExporting] = useState<string | null>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  /* ─── Export helpers ─── */
  const exportPNG = async () => {
    setExporting("png");
    try {
      const { toPng } = await import("html-to-image");
      const canvas = document.getElementById("architecture-canvas");
      if (!canvas) { alert("Architecture not loaded yet."); return; }
      const dataUrl = await toPng(canvas, {
        backgroundColor: "#ffffff",
        quality: 1,
        pixelRatio: 2,
      });
      const link = document.createElement("a");
      const title = architecture?.title || "architecture";
      link.download = `${title.replace(/\s+/g, "-").toLowerCase()}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error("PNG export failed:", err);
    } finally {
      setExporting(null);
      setExportOpen(false);
    }
  };

  const exportPDF = async () => {
    setExporting("pdf");
    try {
      const { toPng } = await import("html-to-image");
      const { default: jsPDF } = await import("jspdf");
      const canvas = document.getElementById("architecture-canvas");
      if (!canvas) { alert("Architecture not loaded yet."); return; }

      const dataUrl = await toPng(canvas, {
        backgroundColor: "#ffffff",
        quality: 1,
        pixelRatio: 2,
      });

      const pdf = new jsPDF("landscape", "mm", "a4");
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const imgProps = pdf.getImageProperties(dataUrl);
      const imgH = (imgProps.height * pageW) / imgProps.width;
      const yOffset = imgH < pageH ? (pageH - imgH) / 2 : 0;

      // Title header
      const title = architecture?.title || "Architecture Diagram";
      pdf.setFontSize(14);
      pdf.setTextColor(30, 30, 50);
      pdf.text(title, 10, 12);
      pdf.setFontSize(9);
      pdf.setTextColor(100, 100, 120);
      pdf.text(`Generated by Arch.AI · ${new Date().toLocaleDateString()}`, 10, 18);

      // Image (below title)
      const imageY = Math.max(22, yOffset);
      pdf.addImage(dataUrl, "PNG", 0, imageY, pageW, Math.min(imgH, pageH - imageY));

      const filename = (architecture?.title || "architecture").replace(/\s+/g, "-").toLowerCase();
      pdf.save(`${filename}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
    } finally {
      setExporting(null);
      setExportOpen(false);
    }
  };

  const exportJSON = () => {
    setExporting("json");
    try {
      const data = {
        title: architecture?.title || "Architecture",
        summary: architecture?.summary || "",
        generatedAt: new Date().toISOString(),
        techStack: architecture?.techStack || [],
        components: (architecture?.nodes as Array<{ id?: string; data?: { label?: string; layer?: string; tech?: string; description?: string } }> || []).map((node) => ({
          id: node.id,
          name: node.data?.label,
          layer: node.data?.layer,
          tech: node.data?.tech,
          description: node.data?.description,
        })),
        relationships: (architecture?.edges as Array<{ id?: string; source?: string; target?: string; label?: string }> || []).map((edge) => ({
          id: edge.id,
          from: edge.source,
          to: edge.target,
          label: edge.label,
        })),
      };
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const link = document.createElement("a");
      const filename = (architecture?.title || "architecture").replace(/\s+/g, "-").toLowerCase();
      link.download = `${filename}.json`;
      link.href = URL.createObjectURL(blob);
      link.click();
      URL.revokeObjectURL(link.href);
    } catch (err) {
      console.error("JSON export failed:", err);
    } finally {
      setExporting(null);
      setExportOpen(false);
    }
  };

  const hasArch = !!(architecture?.nodes?.length);

  return (
    <motion.div
      initial={{ y: -20, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      className="glass-panel absolute left-1/2 top-3 z-20 flex -translate-x-1/2 items-center gap-2 rounded-xl px-3 py-2"
    >
      {/* ── Export dropdown ── */}
      <div className="relative" ref={dropdownRef}>
        <button
          onClick={() => setExportOpen((v) => !v)}
          disabled={!hasArch}
          className="group flex items-center gap-1.5 rounded-lg border border-slate-500/35 bg-slate-900/65 px-2.5 py-1.5 text-xs text-slate-200 transition hover:-translate-y-0.5 hover:border-cyan-300/50 hover:text-cyan-200 disabled:opacity-40 disabled:cursor-not-allowed"
          title={hasArch ? "Export architecture" : "Load an architecture first"}
        >
          <Download size={13} className="transition group-hover:rotate-6" />
          {exporting ? "Exporting…" : "Export"}
        </button>

        <AnimatePresence>
          {exportOpen && (
            <>
              {/* Backdrop */}
              <div className="fixed inset-0 z-40" onClick={() => setExportOpen(false)} />
              <motion.div
                initial={{ opacity: 0, y: -6, scale: 0.97 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: -6, scale: 0.97 }}
                transition={{ duration: 0.15 }}
                className="absolute left-0 top-full mt-2 z-50 min-w-[168px] overflow-hidden rounded-xl border border-slate-500/30 bg-[rgba(10,10,25,0.97)] shadow-2xl"
              >
                <div className="px-3 pt-2 pb-1 text-[9px] font-bold uppercase tracking-widest text-slate-500">
                  Download As
                </div>
                <button
                  onClick={exportPNG}
                  disabled={!!exporting}
                  className="flex w-full items-center gap-2.5 px-3 py-2.5 text-xs text-slate-200 transition hover:bg-indigo-500/10 disabled:opacity-50"
                >
                  <FileImage size={13} className="text-indigo-400 flex-shrink-0" />
                  <span>PNG Image</span>
                  <span className="ml-auto text-[9px] text-slate-500">High-res</span>
                </button>
                <button
                  onClick={exportPDF}
                  disabled={!!exporting}
                  className="flex w-full items-center gap-2.5 px-3 py-2.5 text-xs text-slate-200 transition hover:bg-purple-500/10 disabled:opacity-50"
                >
                  <FileText size={13} className="text-purple-400 flex-shrink-0" />
                  <span>PDF Document</span>
                  <span className="ml-auto text-[9px] text-slate-500">A4 Landscape</span>
                </button>
                <button
                  onClick={exportJSON}
                  disabled={!!exporting}
                  className="flex w-full items-center gap-2.5 px-3 py-2.5 text-xs text-slate-200 transition hover:bg-emerald-500/10 disabled:opacity-50"
                >
                  <FileJson size={13} className="text-emerald-400 flex-shrink-0" />
                  <span>JSON Data</span>
                  <span className="ml-auto text-[9px] text-slate-500">All components</span>
                </button>
              </motion.div>
            </>
          )}
        </AnimatePresence>
      </div>

      {/* Walkthrough */}
      <button
        onClick={onStartWalkthrough}
        className="rounded-lg border border-cyan-300/45 bg-cyan-300/12 px-2.5 py-1.5 text-xs text-cyan-200 transition hover:bg-cyan-300/22"
      >
        <span className="flex items-center gap-1.5">
          <BookOpenCheck size={13} />
          {walkthroughActive ? "Walkthrough On" : "Walkthrough"}
        </span>
      </button>

      {/* Immersive */}
      <button
        onClick={onToggleImmersive}
        className="ml-1 rounded-lg border border-fuchsia-300/45 bg-fuchsia-400/15 px-2.5 py-1.5 text-xs text-fuchsia-200 transition hover:bg-fuchsia-400/28"
      >
        <span className="flex items-center gap-1.5">
          {immersive ? <Sparkles size={13} /> : <Expand size={13} />}
          {immersive ? "Exit Immersive" : "Immersive"}
        </span>
      </button>
    </motion.div>
  );
}
